# Generated by Django 5.0.1 on 2024-01-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='img',
        ),
    ]
